02. HW syntax
sanyco86/go-core pull request #1
Opened 2022-03-22 19:33 UTC by sanyco86

2022-03-23 10:14 UTC, DmitriyVTitov requested changes
Не принято.

2022-03-23 10:14 UTC, DmitriyVTitov commented on 02-syntax/cmd/engine/gosearch.go
> +		fmt.Println("Используйте флаг `s`. Например: gosearch –s Language")
можно ещё вот так: https://pkg.go.dev/flag#PrintDefaults

2022-03-23 10:14 UTC, DmitriyVTitov commented on 02-syntax/cmd/engine/gosearch.go
> +
лишняя пустая, сюда потом кто-то что-то случайно впишет

2022-03-23 10:14 UTC, DmitriyVTitov commented on 02-syntax/cmd/engine/gosearch.go
> +
см. выше

2022-03-23 10:14 UTC, DmitriyVTitov commented on 02-syntax/cmd/engine/gosearch.go
> +			return result, err
вот тут неверно: функция должна вернуть ошибку, а не завершить всю систему!
это - серьёзная ошибка

2022-03-24 11:17 UTC, DmitriyVTitov requested changes
Вызываемые функции не должны паниковать (если для этого нет существенных причин). Представьте, что функции стандартной библиотеки вдруг паниковали бы на пустом месте.

2022-03-24 11:17 UTC, DmitriyVTitov commented on 02-syntax/cmd/engine/gosearch.go
> +		}
всё то же самое, что и в прошлый раз
вызываемая функция вместо возврата ошибки вызывает панику и завершает программу
следует именно возвращать ошибку

2022-03-24 11:30 UTC, sanyco86 commented on 02-syntax/cmd/engine/gosearch.go
> +		}
Достаточно ли? `log.Print(err)` она вроде не вызывает `os.Exit`

2022-03-24 11:46 UTC, DmitriyVTitov commented on 02-syntax/cmd/engine/gosearch.go
> +		}
функция должна **вернуть** ошибку
`return ..., err`

2022-03-24 12:06 UTC, sanyco86 commented on 02-syntax/cmd/engine/gosearch.go
> +		}
то есть я должен собрать все ошибки которые произошли пока выполнялся цикл в один массив и потом после и потом вернуть их ??

2022-03-24 12:19 UTC, DmitriyVTitov approved these changes

2022-03-24 12:19 UTC, DmitriyVTitov commented on 02-syntax/cmd/engine/gosearch.go
> +}
сейчас обработка ошибки верная - достаточно её просто напечатать и продолжить сканирование
в этом случае функция не может вернуть ошибку в принципе, значит надо убрать возврат ошибки из сигнатуры

2022-03-24 12:20 UTC, DmitriyVTitov commented on 02-syntax/cmd/engine/gosearch.go
> +		}
нет, я ошибся, корректно как раз напечатать и продолжить обработку
поправьте сигнатуру и присылайте ответ на задание

2022-03-24 12:24 UTC, sanyco86 commented on 02-syntax/cmd/engine/gosearch.go
> +}
сделать `return result` без `, nil` 
и убрать error из `([]crawler.Document, error)`

Все верно?

2022-03-24 13:20 UTC, DmitriyVTitov commented on 02-syntax/cmd/engine/gosearch.go
> +}
да, раз функция не может вернуть ошибку в принципе, её не должно быть в списке возвращаемых результатов

2022-03-24 13:37 UTC, sanyco86 commented on 02-syntax/cmd/engine/gosearch.go
> +}
я просто ориентировался на вот эту твою функцию и полагал что возврат nil обязательные, даже если ошибок нет

https://github.com/sanyco86/go-core/pull/1/files#diff-f7952ab0302e0eafe16c4d374f79eb66b4f14369de47ebe73d47661db903f0d2R88

2022-03-24 18:04 UTC, merged