03. HW algorithms
sanyco86/go-core pull request #2
Opened 2022-03-24 20:12 UTC by sanyco86

2022-03-25 13:36 UTC, DmitriyVTitov requested changes
нет бинарного поиска

2022-03-25 13:36 UTC, DmitriyVTitov commented on 03-algorithms/cmd/engine/gosearch.go
> +func scan(urls []string, indexDB hash.Index) []crawler.Document {
мне было бы неочевидно требование функции сканирования передать ей целую БД как зависимость
гораздо логичней, если эта функция вернёт просто документы, а уже методами БД их добавить в БД

2022-03-25 13:36 UTC, DmitriyVTitov commented on 03-algorithms/cmd/engine/gosearch.go
> +	return result
вот это вот называется "побочный эффект", причём весьма неочевидный
нужно разделять такие операции

2022-03-25 13:36 UTC, DmitriyVTitov commented on 03-algorithms/go.mod
> +go 1.17
можно установить 1.18, пригодится на курсе

2022-03-25 13:36 UTC, DmitriyVTitov commented on 03-algorithms/cmd/engine/gosearch.go
> +	}
по условиям задания нужно использовать бинарный поиск
да, тут от него толку мало, но таковы требования

2022-03-28 10:57 UTC, DmitriyVTitov requested changes
Функция Search с бинарным поиском объявлена, но нигде не используется.
Кстати, не называйте с большой буквы объекты, которые не предполагается экспортировать.

2022-03-28 10:57 UTC, DmitriyVTitov commented on 03-algorithms/cmd/engine/gosearch.go
> +		err := errors.New("поиск не дал результатов")
ошибка тут выглядит нелогичной: нет результатов - вернули пустой массив

2022-03-28 10:57 UTC, DmitriyVTitov commented on 03-algorithms/cmd/engine/gosearch.go
> +	if index >= len(docs) || docs[index].ID != id {
эта функция нигде не используется

2022-03-28 11:05 UTC, sanyco86 commented on 03-algorithms/cmd/engine/gosearch.go
> +	if index >= len(docs) || docs[index].ID != id {
в 31 строке `doc, err := Search(id, docs)`

2022-03-28 11:12 UTC, sanyco86 commented on 03-algorithms/cmd/engine/gosearch.go
> +		err := errors.New("поиск не дал результатов")
эта ошибка отвечает только за свою функцию, если в пределах функции ничего не найдено, то она вернет ошибку, так как искомого `id` в массиве не найдена, а в пределах всей программы, это бы обозначало, что нужно смотреть функцию которая выдала мне список `ids`. а именно вопрос как в `ids := store.Search(*q)` и выяснять как попал id которого нет в docs

2022-03-28 11:51 UTC, DmitriyVTitov commented on 03-algorithms/cmd/engine/gosearch.go
> +		err := errors.New("поиск не дал результатов")
ОК, понятно
в таких случаях часто возвращают указатель на тип, и если вернуть нечего - возвращают `nil`

2022-03-28 11:52 UTC, DmitriyVTitov approved these changes
Всё ОК, я смотрел невнимательно.

2022-03-28 11:52 UTC, DmitriyVTitov commented on 03-algorithms/cmd/engine/gosearch.go
> +	if index >= len(docs) || docs[index].ID != id {
хм, я проглядел
меня смутил поиск в строке 29

2022-03-28 12:34 UTC, merged